
{
	"conf": {
		"prefix": "conf",
		"body": [
			"RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple",
      "RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list && apt update",
      "RUN sed -i 's/deb.debian.org/mirrors.tuna.tsinghuaedu.cn/g' /etc/apt/sources.list.d/debian.sources"
		]
	}
}
